### PR TITLE
feat: mocha support

### PR DESCRIPTION
**Pull request by fdsimms**

### CODE REVIEW

**Comment by postlight-org** [comment]
<details>
<summary>
<b>1 failed test 😱</b>
</summary>

---

**getTestReport Returns empty string if there are no failed tests**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
AssertionError [ERR_ASSERTION]: '<details><summary><b>1failedtest😱</b></summary>---**basictest**<details><summary>Seewhatwentwrong</summary>```bashError:\u0... == ''
    at Context.it (src/tests/mocha/getTestReport.test.js:21:12)
```

---
  </details>

---
  
</details>

**Comment by postlight-org** [comment]
<details>
<summary>
<b>1 failed test 😱</b>
</summary>

---

**getTestReport Returns empty string if there are no failed tests**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
AssertionError [ERR_ASSERTION]: '<details><summary><b>1failedtest😱</b></summary>---**basictest**<details><summary>Seewhatwentwrong</summary>```bashError:\u0... == ''
    at Context.it (src/tests/mocha/getTestReport.test.js:21:12)
```

---
  </details>

---
  
</details>

**Comment by postlight-org** [comment]
<details>
<summary>
<b>1 failed test 😱</b>
</summary>

---

**getTestReport Returns empty string if there are no failed tests**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
AssertionError [ERR_ASSERTION]: '<details><summary><b>1failedtest😱</b></summary>---**basictest**<details><summary>Seewhatwentwrong</summary>```bashError:\u0... == ''
    at Context.it (src/tests/mocha/getTestReport.test.js:21:12)
```

---
  </details>

---
  
</details>

**Comment by postlight-org** [comment]
<details>
<summary>
<b>1 failed test 😱</b>
</summary>

---

**basic test Returns empty string if there are no failed tests**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
AssertionError [ERR_ASSERTION]: '<details><summary><b>1failedtest😱</b></summary>---**basictest**<details><summary>Seewhatwentwrong</summary>```bashError:\u0... == ''
    at Context.it (src/tests/mocha/getTestReport.test.js:21:12)
```

---
  </details>

---
  
</details>

**Comment by postlight-org** [comment]
<details>
<summary>
<b>2 failed tests 😱</b>
</summary>

---

**basic test Returns empty string if there are no failed tests**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
AssertionError [ERR_ASSERTION]: '<details><summary><b>1failedtest😱</b></summary>---**basictest**<details><summary>Seewhatwentwrong</summary>```bashError:\u0... == ''
    at Context.it (src/tests/mocha/getTestReport.test.js:21:12)
```

---
  </details>

---
  


**basic test Adds 2 + 2**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
AssertionError [ERR_ASSERTION]: 4 == 5
    at Context.it (src/tests/mocha/getTestReport.test.js:24:33)
```

---
  </details>

---
  
</details>

**Comment by postlight-org** [comment]
<details>
<summary>
<b>1 failed test 😱</b>
</summary>

---

**getTestReport Adds 2 + 2**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
assert.equal(received, expected) or assert(received) 

Expected value to be equal to:
  5
Received:
  4
    at Object.equal (/home/circleci/ci-test-failure-reporter/src/tests/getTestReport.test.js:24:33)
    at Object.asyncJestTest (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at resolve (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:41:12)
    at new Promise (<anonymous>)
    at mapper (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at promise.then (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:71:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

---
  </details>

---
  
</details>

**Comment by postlight-org** [comment]
<details>
<summary>
<b>2 failed tests 😱</b>
</summary>

---

**basic test Adds 2 + 2**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
assert.equal(received, expected) or assert(received) 

Expected value to be equal to:
  5
Received:
  4
    at Object.equal (/home/circleci/ci-test-failure-reporter/src/tests/mocha/getTestReport.test.js:24:33)
    at Object.asyncJestTest (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at resolve (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:41:12)
    at new Promise (<anonymous>)
    at mapper (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at promise.then (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:71:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

---
  </details>

---
  


**basic test Adds 2 + 2 again**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
assert.equal(received, expected) or assert(received) 

Expected value to be equal to:
  5
Received:
  4
    at Object.equal (/home/circleci/ci-test-failure-reporter/src/tests/mocha/getTestReport.test.js:25:39)
    at Object.asyncJestTest (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at resolve (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:41:12)
    at new Promise (<anonymous>)
    at mapper (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at promise.then (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:71:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

---
  </details>

---
  
</details>

**Comment by postlight-org** [comment]
<details>
<summary>
<b>2 failed tests 😱</b>
</summary>

---

**basic test Adds 2 + 2**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
AssertionError [ERR_ASSERTION]: 4 == 5
    at Context.it (src/tests/mocha/getTestReport.test.js:16:33)
```

---
  </details>

---
  


**basic test Adds 2 + 2 again**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
AssertionError [ERR_ASSERTION]: 4 == 5
    at Context.it (src/tests/mocha/getTestReport.test.js:17:39)
```

---
  </details>

---
  
</details>

**Comment by postlight-org** [comment]
<details>
<summary>
<b>2 failed tests 😱</b>
</summary>

---

**basic test Adds 2 + 2**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
assert.equal(received, expected) or assert(received) 

Expected value to be equal to:
  5
Received:
  4
    at Object.equal (/home/circleci/ci-test-failure-reporter/src/tests/mocha/getTestReport.test.js:16:33)
    at Object.asyncJestTest (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at resolve (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:41:12)
    at new Promise (<anonymous>)
    at mapper (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at promise.then (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:71:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

---
  </details>

---
  


**basic test Adds 2 + 2 again**
  <details>
  <summary>
    See what went wrong
  </summary>

```bash
assert.equal(received, expected) or assert(received) 

Expected value to be equal to:
  5
Received:
  4
    at Object.equal (/home/circleci/ci-test-failure-reporter/src/tests/mocha/getTestReport.test.js:17:39)
    at Object.asyncJestTest (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at resolve (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:41:12)
    at new Promise (<anonymous>)
    at mapper (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at promise.then (/home/circleci/ci-test-failure-reporter/node_modules/jest-jasmine2/build/queueRunner.js:71:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

---
  </details>

---
  
</details>

**Review by adampash — APPROVED** [review]
This looks great!

**Pull request merged**
